name: property_insurance_plan_viewer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.0
  injectable: ^2.5.0
  intl: ^0.19.0
  easy_localization: ^3.0.7
  provider: ^6.1.2
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  either_dart: ^1.0.0
  mocktail: ^1.0.2
  gap: ^3.0.1
  responsive_builder: ^0.7.1
  provider_test: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.0
  build_runner: 2.4.11
  injectable_generator: 2.6.1
  json_serializable: 6.8.0
  import_sorter: 4.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

import_sorter:
  ignored_files:
    - .+\.g.dart
    - .+\.gr.dart
